project:
  type: website

website:
  page-navigation: true
  title: "Lehre@AMD"
  description: "Willkommen zur Lehre-Homepage der Abteilung Analyse und Modellierung komplexer Daten an der JGU."
  site-url: "https://github.com/JoseAlanis/amdstatsem"
      
  page-footer:
    right: "This page is built with 💛️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022-2023, authors of [Lehre@AMD](https://github.com/JoseAlanis/amdstatsem)"
    background: "#C1002A"
    
  sidebar:
    background: "#C1002A"
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/JoseAlanis/amdstatsem
        text: "Code auf GitHub"
      - icon: journal-text
        href: https://methoden.amd.psychologie.uni-mainz.de/lehre/
        text: "AMD Lehre"
      - icon: person-fill
        href: https://methoden.amd.psychologie.uni-mainz.de/abteilungsmitglieder/
        text: "Kontakt"
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Seminar Multi-Level Modelle"
        contents:
        - href: about/about_MLM_sose23.qmd
          text: "1. Allgemeine Informationen"
        - href: mlm_seminar_sose_23/hierarchische_daten.qmd
          text: "2. Hierarchische Daten"
      - section: "Seminar kognitive Modellierung"
        contents: 
          - section: "Allgemeine Informationen"
            contents:
              - href: about/about_jan.qmd
                text: "Kursinhalt und Tutorium"
          - section: "Termin 1: Organisation"
            contents: 
              - href: cogmod_sem_sose23/Termin1.qmd
                text: "Zusammenfassung"
              - href: https://slides.com/gman_science/introduction-organisation?token=4Pkkol6P
                text: "Slides"
          - section: "Termin 2: Einführung I"
            contents:
              - href: 
                text: "Zusammenfassung"
              - href: https://slides.com/gman_science/introduction-why-models?token=r4ID0G6o
                text: "Slides"
              - href: 
                text: "Weiterführende Literatur"
            
            
          
     
        
          
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [darkly, theme-dark.scss]
    toc: true
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap

freeze: auto

editor: visual

