project:
  type: website

website:
  page-navigation: true
  title: "AMD Stats"
  description: "Homepage für 02.132.6110 Seminar: Fortgeschrittene statistische Methoden II in WiSe 22/23 an der JGU."
  site-url: "https://josealanis.github.io/stats-website-template/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022-2023, Autoren von AMD Stats"
    background: "#C1002A"

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap

freeze: auto

editor: visual

