project:
  type: website

website:
  page-navigation: true
  title: "Fortgeschrittene statistische Methoden II"
  description: "Homepage für die Seminareder Arbeitsgruppe AMD an der JGU."
  site-url: "https://github.com/JoseAlanis/amdstatsem"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022-2023, authors of [AMD-stat-sem](https://github.com/JoseAlanis/amdstatsem)"
    background: "#C1002A"
  
  sidebar:
    background: "#C1002A"
    # logo: "<add_logo>"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/JoseAlanis/amdstatsem
        text: "GitHub Repository"
      - icon: journal-text
        href: https://methoden.amd.psychologie.uni-mainz.de/lehre/
        text: "Lehre AMD"
        
    style: "docked"
    search: true
    collapse-level: 1

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap

freeze: auto

editor: visual

